apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-prod-deployment
  labels:
    app: my-app-prod
  namespace: default
spec:
  replicas: 1 # from-param: ${replicaCount}
  selector:
    matchLabels:
      app: my-app-prod
  template:
    metadata:
      labels:
        app: my-app-prod
    spec:
      containers:
      - name: nginx
        image: my-app-image
        ports:
        - containerPort: 8080